### PR TITLE
Fixes for PostgreSQL 11

### PR DESCRIPTION
**Pull request by deem0n**
Hi, it's my first commit and first Smalltalk code I've written for many years since 2001. Please do any fixes you may find appropriate!

I see there are more things to fix, would you accept more PR?

Sorry for duplicate commit, Pharo get stuck with ssh keys and I was unable to recover it flawlessly.

### CODE REVIEW

**Comment by deem0n** [comment]
Please wait, proisagg was BOOL type and prokind is char!
Need to deal with it.
https://www.postgresql.org/docs/11/catalog-pg-proc.html

**Comment by deem0n** [comment]
Now it is working!

**Comment by juliendelplanque** [comment]
Ho Hello, I haven't seem this PR while commenting on the other. :-)

I will check it and merge. :-)

**Comment by deem0n** [comment]
Any chance to merge it ?

**Comment by juliendelplanque** [comment]
@deem0n done. :-)

**Pull request merged**
